version: 2

builds:
  - id: linux
    main: ./main.go
    goos: [linux]
    goarch: [amd64]
    dir: .
    binary: workflow_monitor
    flags: ["-v"]

archives:
  - id: default
    builds: [linux]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yml
      - bin/**

release:
  github:
    owner: "MA-DOS"
    name: "LowLevelMonitoring"

version:
  git_tag: true