version: 2

builds:
  - id: linux
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -v
    artifacts:
      - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz"
        format: tar.gz
        files:
          - ./bin/*

release:
  draft: false
  prerelease: false
  github:
    owner: "MA-DOS"
    name: "LowLevelMonitoring"
