server_configurations:
  config_path: config/config.yml
  prometheus:
    target_server:
      address: "http://192.168.2.128:9090"
      timeout: 10s
      interval: 5
monitoring_targets:
  task_metadata:
    enabled: true
    data_sources:
    - source: cAdvisor
      metrics:
      - name: container_task_state
        query: max_over_time(container_tasks_state[60s])
      - name: container start-time
        query: max_over_time(container_start_time_seconds[10s])
  cpu:
    enabled: false
    data_sources:
    - source:
      metrics:
      - name:
        query:
  memory:
    enabled: false
    data_sources:
    - source:
      metrics:
      - name:
        query:
  disk:
    enabled: false
    data_sources:
    - source:
      metrics:
      - name:
        query:
  network:
    enabled: false
    data_sources:
    - source:
      metrics:
      - name:
        query:
  energy:
    enabled: false
    data_sources:
    - source:
      metrics:
      - name:
        query:
