server_configurations:
  config_path: config/config.yml
  prometheus:
    target_server:
      address: "http://192.168.2.128:9090"
      timeout: 10s
      interval: 0.5
monitoring_targets:
  task_metadata:
    enabled: true
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
    - name: slurm_job_id
      query: slurm_job_id
  cpu:
    enabled: false
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
    - name: slurm_job_id
      query: slurm_job_id
    - name: slurm_job_id
      query: slurm_job_id
    - name: slurm_job_id
      query: slurm_job_id
  memory:
    enabled: false
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
  disk:
    enabled: false
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
  network:
    enabled: false
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
  energy:
    enabled: false
    metrics:
    - name: slurm_job_id
      query: slurm_job_id
