server_configurations:
  config_path: ~/dev/LowLevelMonitoring/config.yml
  prometheus:
    target_server:
      address: "http://192.168.2.128:9090"
      timeout: 10s
      interval: 5
monitoring_targets:
  task_metadata:
    enabled: true
    data_sources:
    - source: cAdvisor_meta
      metrics:
      - name: container_task_state
        query: max_over_time(container_tasks_state[60s])
  cpu:
    enabled: true
    data_sources:
    - source: cAdvisor_cpu
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
    - source: cAdvisor_cpu_2
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
  memory:
    enabled: true
    data_sources:
    - source: cAdvisor_memory
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
  disk:
    enabled: true
    data_sources:
    - source: cAdvisor_disk
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
  network:
    enabled: true
    data_sources:
    - source: cAdvisor_network
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
  energy:
    enabled: true
    data_sources:
    - source: cAdvisor_energy
      metrics:
      - name: container_start-time
        query: max_over_time(container_start_time_seconds[10s])
    - source:
      metrics:
      - name:
        query:
