server_configurations:
  config_path: ~/dev/LowLevelMonitoring/config.yml
  prometheus:
    target_server:
      address: "http://192.168.2.128:9090"
      timeout: 10s
      interval: 1
monitoring_targets:
  task_metadata:
    enabled: true
    data_sources: 
    - source: cAdvisor
      metrics:
      - name: container_tasks_state
        query: max_over_time(container_tasks_state{name=~"nxf-.*"}[5s])
      - name: container start-time
        query: max_over_time(container_start_time_seconds{name=~"nxf-.*"}[5s])
    - source: slurm-job-expoter
      metrics:
      - name: slurm-job-information
        query: slurm_job_id
  cpu:
    enabled: true
    data_sources:
    - source: cAdvisor 
      metrics:
      - name: container_cpu_usage_seconds_total
        query: max_over_time(container_cpu_usage_seconds_total{name=~"nxf-.*"}[10s])
      - name: container_cpu_load_average_10s
        query: max_over_time(container_cpu_load_average_10s{name=~"nxf-.*"}[10s])
    - source: cgroups-exporter
      metrics:
      - name: cgroups_cpu_pressure_full_total
        query: max_over_time(cgroups_cpu_pressure_full_total[10s])
      - name: cgroups_pids_count
        query: max_over_time(cgroups_pids_count[10s])
    - source: scaphandre
      metrics:
      - name: scaph_process_cpu_usage_percentage
        query: max_over_time(scaph_process_cpu_usage_percentage{container_scheduler=~"docker"}[10s]) 
    - source: node-exporter
      metrics:
      - name: node_cpu_core_throttles_total
        query: node_cpu_core_throttles_total
      - name: node_cpu_scaling_frequency_hertz
        query: node_cpu_scaling_frequency_hertz
      - name: node_cpu_seconds_total
        query: node_cpu_seconds_total
      - name: node_pressure_cpu_waiting_seconds_total
        query: node_pressure_cpu_waiting_seconds_total
  memory:
    enabled: false
    data_sources:
    - source: cAdvisor
      metrics:
      - name: container_memory_usage_bytes
        query: max_over_time(container_memory_usage_bytes{name=~"nxf-.*"}[10s])
      - name: container_memory_failures_total
        query: max_over_time(container_memory_failures_total{name=~"nxf-.*"}[10s])
      - name: container_memory_rss
        query: max_over_time(container_memory_rss{name=~"nxf-.*"}[10s])
      - name: container_memory_working_set_bytes
        query: max_over_time(container_memory_working_set_bytes{name=~"nxf-.*"}[10s])
    - source: cgroups-exporter
      metrics:
      - name: cgroups_memory_usage
        query: max_over_time(cgroups_memory_usage[10s])
      - name: cgroups_memory_pressure_full_total
        query: max_over_time(cgroups_memory_pressure_full_total[10s])
    - source: scaphandre
      metrics:
      - name: scaph_process_memory_bytes
        query: max_over_time(scaph_process_memory_bytes{container_scheduler=~"docker"}[10s])
      - name: scaph_process_memory_virtual_bytes
        query: max_over_time(scaph_process_memory_virtual_bytes{container_scheduler=~"docker"}[10s])
    - source: node-exporter
      metrics:
      - name: node_pressure_memory_waiting_seconds_total
        query: node_pressure_memory_waiting_seconds_total
  disk:
    enabled: false
    data_sources:
    - source: cAdvisor
      metrics:
      - name: container_blkio_device_usage_total
        query: max_over_time(container_blkio_device_usage_total{name=~"nxf-.*"}[10s])
      - name: container_fs_io_current
        query: max_over_time(container_fs_io_current{name=~"nxf-.*"}[10s])
      - name: container_fs_io_time_seconds_total
        query: max_over_time(container_fs_io_time_seconds_total{name=~"nxf-.*"}[10s])
      - name: container_fs_io_time_weighted_seconds_total
        query: max_over_time(container_fs_io_time_weighted_seconds_total{name=~"nxf-.*"}[10s])
      - name: container_fs_writes_total
        query: max_over_time(container_fs_writes_total{name=~"nxf-.*"}[10s])
      - name: container_fs_reads_total
        query: max_over_time(container_fs_reads_total{name=~"nxf-.*"}[10s])
      - name: container_fs_reads_bytes_total
        query: max_over_time(container_fs_reads_bytes_total{name=~"nxf-.*"}[10s])
      - name: container_fs_writes_bytes_total
        query: max_over_time(container_fs_writes_bytes_total{name=~"nxf-.*"}[10s])
      - name: container_fs_limit_bytes
        query: max_over_time(container_fs_limits_bytes_total{name=~"nxf-.*"}[10s])
    - source: cgroups-exporter
      metrics:
      - name: cgroups_io_pressure_full_total
        query: max_over_time(cgroups_io_pressure_full_total[10s])
    - source: scaphandre
      metrics:
        - name: scaph_process_disk_total_read_bytes
          query: max_over_time(scaph_process_disk_total_read_bytes{container_scheduler=~"docker"}[10s])
        - name: scaph_process_disk_total_write_bytes
          query: max_over_time(scaph_process_disk_total_write_bytes{container_scheduler=~"docker"}[10s])
    - source: node-exporter
      metrics:
      - name: node_disk_io_time_seconds_total
        query: node_disk_io_time_seconds_total
      - name: node_disk_writes_completed_total
        query: node_disk_writes_completed_total
      - name: node_disk_read_bytes_total
        query: node_disk_read_bytes_total
      - name: node_disk_reads_completed_total
        query: node_disk_reads_completed_total
      - name: node_disk_written_bytes_totaly
        query: node_disk_written_bytes_total
      - name: node_disk_write_time_seconds_total
        query: node_disk_write_time_seconds_total
      - name: node_disk_writes_completed_total
        query: node_disk_writes_completed_total
      - name: node_nfsd_disk_bytes_written_total
        query: node_nfsd_disk_bytes_written_total
      - name: node_nfsd_disk_bytes_read_total
        query: node_nfsd_disk_bytes_read_total
      - name: node_pressure_io_waiting_seconds_total
        query: node_pressure_io_waiting_seconds_total
  network:
    enabled: false
    data_sources:
    - source: cAdvisor
      metrics:
      - name: container_network_receive_bytes_total
        query: max_over_time(container_network_receive_bytes_total{name=~"nxf-.*"}[10s])
      - name: container_network_receive_packets_dropped_total
        query: max_over_time(container_network_receive_packets_dropped_total{name=~"nxf-.*"}[10s])
      - name: container_network_receive_packets_total
        query: max_over_time(container_network_receive_packets_total{name=~"nxf-.*"}[10s]) 
      - name: container_network_transmit_bytes_total
        query: max_over_time(container_network_transmit_bytes_total{name=~"nxf-.*"}[10s])
      - name: container_network_transmit_errors_total
        query: max_over_time(container_network_transmit_errors_total{name=~"nxf-.*"}[10s])
    - source: node-exporter
      metrics:
      - name: node_network_transmit_packets_total
        query: node_network_transmit_packets_total
      - name: node_network_receive_bytes_total
        query: node_network_receive_bytes_total
  energy:
    enabled: false
    data_sources:
    - source: slurm-job-expoter
      metrics:
      - name: slurm-job-energy
        query: slurm_job_id
    - source: scaphandre
      metrics:
      - name: scaph_host_energy_microjoules
        query: scaph_host_energy_microjoules 
      - name: scaph_host_power_microwatts
        query: scaph_host_power_microwatts
      - name: scaph_process_power_consumption_microwatts
        query: max_over_time(scaph_process_power_consumption_microwatts{container_scheduler=~"docker"}[10s])
    - source: node-exporter
      metrics:
      - name: node_cooling_device_cur_state
        query: node_cooling_device_cur_state
      - name: node_cooling_device_max_state
        query: node_cooling_device_max_state
      - name: node_hwmon_temp_celsius
        query: node_hwmon_temp_celsius
      - name: node_hwmon_temp_max_celsius
        query: node_hwmon_temp_max_celsius
