global:
  scrape_interval: 500ms

scrape_configs:
  - job_name: "node exporter"
    static_configs:
      - targets:
          - "192.168.2.128:9100"

  - job_name: "cAdvisor"
    scrape_interval: 100ms
    static_configs:
      - targets:
          - "192.168.2.128:8081"

  - job_name: "cgroups exporter"
    scrape_timeout: 3s
    scrape_interval: 3s
    static_configs:
      - targets:
          - "192.168.2.128:9753" 
 
  - job_name: "slurm-job exporter"
    static_configs:
      - targets:
          - "192.168.2.128:8082"

  - job_name: "process exporter"
    scrape_timeout: 3s
    scrape_interval: 3s
    static_configs:
      - targets: 
          - "192.168.2.128:9256"
           
  - job_name: "scaphandre"
    scrape_interval: 2s  # override to allow more time between scrapes
    fallback_scrape_protocol: "PrometheusText0.0.4"
    static_configs:
      - targets: ["192.168.2.128:8080"]

  - job_name: "cgroups-slurm"
    scrape_interval: 5s  # override to allow more time between scrapes
    fallback_scrape_protocol: "PrometheusText0.0.4"
    static_configs:
      - targets: ["192.168.2.128:9821"]

  - job_name: "docker-activity"
    scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    static_configs:
      - targets: ["192.168.2.128:9091"]

  - job_name: 'ceems_exporter'
    static_configs:
      - targets: ['192.168.2.128:9010']


